

INSERT INTO Classe(codc,ordine,tiposcuola,docrif,scuola)
VALUES('1','secondario','superiore','1','1')
INSERT INTO dispositivo(coddisp,tipo,codreplica)
VALUES('3','sensore','1')
INSERT INTO infoambientali(codinfo,largchioma,lungchioma,pesofrescochioma,pesoseccochioma,altpianta,lungradici,pesofrescoradici,pesoseccoradici,numfiori,numfrutti,numfogliedann,superfdann,ph,umidità,temperatura)
VALUES('1','12,5','21,7','0,5','0,3','11,2','31,3','1,3','1,1','0','0','0','0','20','21')
INSERT INTO orto(codorto,nome,tipo,gps,superf,pulito,adattocontrollo,scuola)
VALUES('10','boccadasse','vaso','44-8','30','true','true','3','1')
INSERT INTO Persona(codp,nome,cognome,email,telefono,ruolo,referenteprog,partecipaprogfin,codmec)
VALUES('1','marco','rossi','marcorossi@hmail.com','3362857984','docente','true','false','')
INSERT INTO replica(codreplica,gruppo,datadimora,esposizione,speciepianta,classedimora,orto,dispositivo)
VALUES('1','alpha',)
INSERT INTO rilevazione(codr,datarilev,datains,respins,modacquisizione,infoamb,dispositivo,resprilev)
VALUES('')
INSERT INTO Scuola(codmec,nome,prov,cicloistruz,finanziamento,tipofin,collabora,,referente)
VALUES('')
INSERT INTO Specie(nomescientifico,nomecomune,scopo,totrepliche)
VALUES('')
