set search_path to 'Progetto_BD2023';

--DA VEDERE TIPI CODICI/CHIAVI

CREATE TABLE Persona
(CodP INTEGER PRIMARY KEY,
 Nome VARCHAR(20) NOT NULL,
 Cognome VARCHAR(20) NOT NULL,
 Email VARCHAR(32) NOT NULL,
 Telefono VARCHAR(16),
 Ruolo VARCHAR(32) NOT NULL,
 ReferenteProg BOOLEAN NOT NULL,
 PartecipaProgFin BOOLEAN NOT NULL,
 Scuola INTEGER, --FOREIGN KEY to add with ALTER TABLE
);

CREATE TABLE Scuola
(CodMec INTEGER PRIMARY KEY,
 Nome VARCHAR(20) NOT NULL,
 Prov CHAR(2) NOT NULL,
 CicloIstruz VARCHAR(32) NOT NULL,
 Finanziamento BOOLEAN NOT NULL,
 TipoFin VARCHAR(32),
 Collabora BOOLEAN NOT NULL,
 Referente INTEGER,
 FOREIGN KEY (Referente) REFERENCES Persona(CodP) --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
);

ALTER TABLE Persona ADD CONSTRAINT fk_persona_scuola
FOREIGN KEY (Scuola) REFERENCES Scuola(CodMec); --ON UPDATE CASCADE, ON DELETE SET NULL

CREATE TABLE Classe
(CodC INTEGER PRIMARY KEY,
 Ordine VARCHAR(32) NOT NULL,
 TipoScuola VARCHAR(48) NOT NULL,
 DocRif INTEGER,
 Scuola INTEGER,
 FOREIGN KEY (DocRif) REFERENCES Persona(CodP), --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (Scuola) REFERENCES Scuola(CodMec) --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
);

CREATE TABLE Responsabile
(CodResp INTEGER PRIMARY KEY,
 Tipo VARCHAR(16) NOT NULL CHECK (Tipo IN ('Persona', 'Classe')),
 IndividuoResp INTEGER,
 ClasseResp INTEGER,
 FOREIGN KEY (IndividuoResp) REFERENCES Persona(CodP), --ON UPDATE CASCADE
 FOREIGN KEY (ClasseResp) REFERENCES Classe(CodC) --ON UPDATE CASCADE
);

CREATE TABLE InfoAmbientali
(CodInfo INTEGER PRIMARY KEY,
 LargChioma REAL NOT NULL,
 LungChioma REAL NOT NULL,
 PesoFrescoChioma FLOAT(3) NOT NULL,
 PesoSeccoChioma FLOAT(3) NOT NULL,
 AltPianta REAL NOT NULL,
 LungRadici REAL NOT NULL,
 PesoFrescoRadici FLOAT(3) NOT NULL,
 PesoSeccoRadici FLOAT(3) NOT NULL,
 NumFiori INTEGER NOT NULL,
 NumFrutti INTEGER NOT NULL,
 NumFoglieDann INTEGER NOT NULL,
 SuperfDann DOUBLE PRECISION NOT NULL,
 pH DOUBLE PRECISION NOT NULL,
 Umidità INTEGER NOT NULL,
 Temperatura REAL NOT NULL
);

CREATE TABLE Specie
(NomeScientifico VARCHAR(40) PRIMARY KEY,
 NomeComune VARCHAR(30) NOT NULL,
 Scopo VARCHAR(16) NOT NULL CHECK (Scopo IN ('Biomonitoraggio', 'Fitobotanica')),
 TotRepliche INTEGER NOT NULL
);

CREATE TABLE Orto
(CodOrto INTEGER PRIMARY KEY,
 Nome VARCHAR(20) NOT NULL,
 Tipo VARCHAR(16) NOT NULL CHECK (Tipo IN ('Vaso', 'Pieno Campo')),
 GPS FLOAT(10) NOT NULL,
 Superf DOUBLE PRECISION NOT NULL,
 Pulito BOOLEAN NOT NULL,
 AdattoControllo BOOLEAN NOT NULL,
 NumSensori INTEGER NOT NULL,
 TipoSensori VARCHAR(16) NOT NULL CHECK (TipoSensori IN ('Sensore', 'Arduino')),
 Scuola INTEGER,
 FOREIGN KEY (Scuola) REFERENCES Scuola(CodMec) --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
);

CREATE TABLE Replica
(IDReplica INTEGER PRIMARY KEY,
 Gruppo VARCHAR(40) NOT NULL,
 DataDimora DATE NOT NULL,
 Esposizione VARCHAR(16) NOT NULL CHECK (Esposizione IN ('Sole', 'Ombra', 'MezzOmbra')),
 SpeciePianta VARCHAR(40),
 ClasseDimora INTEGER, --NOT NULL
 Orto INTEGER,
 Dispositivo INTEGER,
 FOREIGN KEY (SpeciePianta) REFERENCES Specie(NomeScientifico), --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (ClasseDimora) REFERENCES Classe(CodC), --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (Orto) REFERENCES Orto(CodOrto) --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (Dispositivo) REFERENCES Dispositivo(IDDisp) --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
);

CREATE TABLE Dispositivo
(IDDisp INTEGER PRIMARY KEY,
 Tipo VARCHAR(16) NOT NULL CHECK (Tipo IN ('Sensore', 'Arduino')),
);

CREATE TABLE Rilevazione
(CodR INTEGER PRIMARY KEY,
 DataRilev TIMESTAMP NOT NULL,
 DataIns TIMESTAMP NOT NULL,
 RespIns VARCHAR(40),
 ModAcquisizione VARCHAR(16) NOT NULL CHECK (ModAcquisizione IN ('App', 'Base di Dati')),
 InfoAmb INTEGER,
 Dispositivo INTEGER,
 RespRilev INTEGER,
 FOREIGN KEY (InfoAmb) REFERENCES InfoAmbientali(CodInfo), --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (Dispositivo) REFERENCES Dispositivo(IDDisp), --NOT NULL, ON UPDATE CASCADE, ON DELETE CASCADE
 FOREIGN KEY (RespRilev) REFERENCES Responsabile(CodResp) --NOT NULL ...?, ON UPDATE CASCADE, ON DELETE ...?
 --FOREIGN KEY RespIns									  --NOT NULL ...?, ON UPDATE CASCADE, ON DELETE...?
);